### ISSUE TITLE
Problem with utils.nth_day_of_month

### ISSUE THREAD

**Issue by pgr123** [fitnr/convertdate#21]
I have an error when I try to get the last sunday of March 2019 
I do 
```
from convertdate import holidays,gregorian,utils
an = 2019
SUN = 6
MARS = 3
he = utils.nth_day_of_month(0, SUN, MARS, an)
```
and I get 
he
(2019, 3, 24)

But the last sunday of march 2019 is the 31 and not the 24 !
How can I correct this problem.
Why that happens ?
Thank you.

Pascal

**Comment by pgr123** [comment]
Nobody is here ?
Nobody knows how to correct that bug ?
Is convertdate still alive ?
Please, help me !
Pascal

**Comment by pgr123** [comment]
So I think really that convertdate is definitely dead !
It is a pity ! It was good, but it seems there is nobody on the forum, so it is now unusable !
Pascal

**Comment by fitnr** [comment]
@pgr123 Thank you for reporting this bug, it has been fixed.
In the future, you may find a small amount of patience helpful when communicating with the maintainers of open-source libraries.
