### ISSUE TITLE
Confusing example in README

### ISSUE THREAD

**Issue by andy-z** [fitnr/convertdate#28]
Just started looking at the `convertdate` and the very first example in the README file confused me because it shows that returned tuple contains four numbers:
```
french_republican.from_gregorian(2014, 10, 31)
# (223, 2, 1, 9)
```
When I installed it and tried to run this example I got sort of what I expected:
```
>>> french_republican.from_gregorian(2014, 10, 31)
(223.0, 2, 9)
```
Though floating point year is also a bit confusing. Is the year supposed to be an integer?

**Comment by fitnr** [comment]
The readme issue is a typo.

The return type should indeed be `int`. This will be fixed in the next release.
