### ISSUE TITLE
Some US Federal holidays are incorrect and/or incomplete.

### ISSUE THREAD

**Issue by tsx** [fitnr/convertdate#30]
- [Washington's Birthday](https://github.com/fitnr/convertdate/blob/master/convertdate/holidays.py#L61) is celebrated on 3rd Monday, not a fixed 22nd ([source](https://en.wikipedia.org/wiki/Washington%27s_Birthday)).
- Other fixed US Federal holidays such as [New Years](https://github.com/fitnr/convertdate/blob/master/convertdate/holidays.py#L41), [Veterans Day](https://github.com/fitnr/convertdate/blob/master/convertdate/holidays.py#L197) and [Christmas](https://github.com/fitnr/convertdate/blob/master/convertdate/holidays.py#L229) are missing "observed" flag that moves them to a nearest weekday similar to one [Independence Day](https://github.com/fitnr/convertdate/blob/master/convertdate/holidays.py#L161) implementation has.

**Comment by fitnr** [comment]
Good catch. I'm pushing an update to this today.
