### ISSUE TITLE
Islamic Julian Day conversion incorrect for julian day < 1948085.5

### ISSUE THREAD

**Issue by xayhewalo** [fitnr/convertdate#40]
Title
```
>>> convertdate.islamic.from_jd(1948085.5)
(0, 1, 1)  # correct

>>> convertdate.islamic.from_jd(1948084.5)
(0, 0, 29)
```

There should be a warning in the documentation   # wrong

**Comment by fitnr** [comment]
This is similar to issue #29.

Do you think the method should raise a `Warning` or even an `Exception` for dates before the Islamic epoch?

**Comment by xayhewalo** [comment]
@fitnr , for backwards compatibility the next release should warn the a future release will raise an error. Then sometime in the future have the method actually raise
