### ISSUE TITLE
julian.leap() always truthy for  BC years

### ISSUE THREAD

**Issue by xayhewalo** [fitnr/convertdate#43]
Apologizes for the bombardment of issues, but i don't think `julian.leap` is doing what it's supposed to. The readme says the Julian calendar is proleptic before 4 CE, but the `leap` method always returns `3` for negative years, implying all BC years are leap years which I don't think is the intention.

I'm guessing the intended leap year function is:

```python
def leap(year):
    return year % 4 == 0
```

However, `julian.leap` is used in `julian.monthlength` which is used in `julian.legal_date` which is used in `julian.to_jd`, so changing this leap year method could effect conversions. So does the leap method serve some other purpose I'm not aware?

**Comment by fitnr** [comment]
You're correct. I've added a bugfix for the next version.
