### ISSUE TITLE
Human Era support

### ISSUE THREAD

**Issue by ocket8888** [fitnr/convertdate#44]
I'd like to request support for the [Human Era (or Holocene Era) calendar](https://en.wikipedia.org/wiki/Holocene_calendar)

**Comment by fitnr** [comment]
> The Holocene calendar, also known as the Holocene Era or Human Era (HE), is a year numbering system that adds exactly 10,000 years to the currently dominant

The following code snippet will add compatibility:
```python
holocene_year = gregorian_year + 10000
```
