### ISSUE TITLE
LGPL-3.0 dependency

### ISSUE THREAD

**Issue by dnhkng** [fitnr/convertdate#52]
I just scanned the dependencies, and found that the Pymeeus package used by convertdate is licenced under the LGPL-3.0 License.

Is there a possible replacement we could make here?

[Pymeeus Licence](https://github.com/architest/pymeeus/blob/master/LICENSE.txt) 

Maybe this could be an alternative?
https://github.com/pavolgaj/AstroAlgorithms4Python

**Comment by fitnr** [comment]
Issues are for reporting problems, not requesting substantial changes without a reason.
