### ISSUE TITLE
Contextual Version Conflict

### ISSUE THREAD

**Issue by jamb0ss** [fitnr/convertdate#8]
This condition: `'pytz >= 2014.10, <2016'` in your `setup.py` config seems to break a complex setup, when other lib already depends on the last `pytz` version:

`pkg_resources.ContextualVersionConflict: (pytz 2016.10 (.venv/lib/python2.7/site-packages), Requirement.parse('pytz<2016,>=2014.10'), set(['convertdate']))`

**Comment by fitnr** [comment]
Fixed by [extending the range of accepted `pytz` versions](https://github.com/fitnr/convertdate/commit/e7880ab586f83f086b6c86ad3d20b86986861c7f). I've published convertdate v2.0.9 to PyPi with this change.
